name: Build Kivy iOS App
on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-14 # macOS runner required for Xcode
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          # Install macOS build tools and explicitly provide ios-deploy
          brew install autoconf automake libtool pkg-config ios-deploy
          
          # Upgrade your core Python packaging tools 
          python -m pip install --upgrade pip setuptools wheel
          
          # Reinstall the required python toolchains
          pip install Cython==3.0.11 buildozer
          pip install pbxproj openstep_parser packaging




      - name: Decode Secrets
        run: |
          echo "$IOS_DISTRIBUTION_CERTIFICATE" | base64 --decode > ios_distribution.cer
          echo "$IOS_PROVISIONING_PROFILE" | base64 --decode > app.mobileprovision

      - name: Build with Buildozer
        env:
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        run: |
          buildozer ios debug

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-iOS-Application # Name of the zip file you download from GitHub
          path: bin/*.ipa            # Automatically grabs any .ipa inside the Buildozer bin folder
          if-no-files-found: error   # Fails the pipeline cleanly if the compilation didn't make an ipa
          retention-days: 14
